git:
  repo:
    base: ${GIT_REPO_BASE:https://github.com/maxbarboz/simple-project-java.git}
    destino: ${GIT_REPO_DESTINO:https://github.com/maxbarboz/name-default.git}
  owner: ${GIT_OWNER:maxbarboz}
  repoName: ${GIT_REPO_NAME:name-default}
  branch: ${GIT_BRANCH:main}
  user: ${GIT_USER:maxbarboz}
  token: ${GIT_TOKEN}

github:
  api-url: https://api.github.com

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  codec:
    jackson:
      enabled: true