git:
  repoBase: ${GIT_REPO_BASE}
  repoDestino: ${GIT_REPO_DESTINO:repo-default}
  owner: ${GIT_OWNER}
  repoName: ${GIT_REPO_NAME:name-default}
  branch: ${GIT_BRANCH:main}
  user: ${GIT_USER}
  token: ${GIT_TOKEN}

github:
  api-url: https://api.github.com

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  codec:
    jackson:
      enabled: true