name: Build and Run Java Project

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Load .env to environment
        run: |
          set -a
          source .env
          set +a
          # Export all env vars to GITHUB_ENV to make them available in 'if' and subsequent steps
          printenv | grep -v "GITHUB_ENV" >> $GITHUB_ENV

      - name: Build with Maven
        if: env.execute == 'true'
        run: mvn clean package

      - name: Run the application
        if: env.execute == 'true'
        run: java -jar target/*.jar
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
